spring:
 mvc:
    view:
      suffix: .html
      prefix: /
 h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
 datasource:
   url: jdbc:h2:mem:GroceryStoreDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
   username: sa
   password: null
   driver-class-name: org.h2.Driver
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: none
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

debug: true

server:
  port: 9082       
